name: Deploy to neocities
on: push
concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: deploying to neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        dist_dir: neocities
        cleanup: true