name: Deploy to neocities

on:
  push:
    branches:
      - main
  
concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: Writing blog file
    #   uses: /.github/markdown-html-insert
    #   with:
    #     md-dir: /neocities/blog/md/
    #     template: /neocities/blog/template.html
    #     output: /neocities/blog/index.html

    - name: Deploying to Neocities
      uses: bcomnes/deploy-to-neocities@v1.1.21
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
        dist_dir: neocities